### ISSUE TITLE
Changing a panel twice will corrupt history

### ISSUE THREAD

**Issue by sstraus** [frequent/multiview#40] opened 2012-08-21 22:10 UTC
If i call twice this changepage function

$.mobile.changePage('#side_list', { pageContainer: $('div:jqmData(id="menu")') });

the back button will switch the panel to a blank page.

**Comment by frequent** [comment] 2012-08-22 07:22
Just to reconfirm: 

You are in MENU and changepage to MENU-page2 then to MENU-page3, then click the browser back button OR multiview back button?

Thanks

**Comment by sstraus** [comment] 2012-08-22 08:33
I have a callback in the main page that will refresh the menu panel to ensure list visibility. Sometimes happen that the menu page is already displayed, so the changepage fire on the same page twice. In this case, the rback button of the menu panel will go back to a blank page.

I have also many troubles with the menu panel in portailt. Firing a pagechange in the poped up menu, will close the popup instad of just changing the page. Moreover after this behaviour something goes wrong with the plugin because the menu will open again on the first page, and other dialogs are not popping up anymore.

In landscape works as expected.

Thank you!

**Comment by frequent** [comment] 2012-08-22 08:43
Ok. I'm sitting on a bug with panel navigation and JQM 1.2. Let's see if I can get it fixed and if that also helps in your case. 

Still you have to beware: ChangePage does a lot of things like creating entries in JQM history etc. so calling it randomly is probably not the best thing (same as it was with calling `page()` in earlier JQM versions, this re-initiated the whole page and multiplied all elements potentially - 1,2,4,16 buttons instead of one button).

Question: In case changePage gets called twice on the same page, can you check in Firebug if the page you are "re-changepaging" is in the DOM once or twice? 

Portrait/Landscape I'm also looking at (see issue 39). I don't have my iPad here to test right now though).

**Comment by sstraus** [comment] 2012-08-22 09:48
pagebeforechange is invoked twice. Once with the ui.toPage as string and once as object.
I tried to block the pagebeforechange if the page is already the active one with preventdefault, but the history is still broken.

**Comment by frequent** [comment] 2012-08-22 10:01
this is regular JQM procedure, because when you go from page A to page B using JQM AJAX your URL will in change from

```
   www.yourpage.com/page_1.html
```

to 

```
   www.yourpage.com/page_1.html/#page2.html   (by JQM $window.on('hashChange'... passes string
```

to 

```
  www.yourpage.com/page2.html  (done by JQM pushState, passes object
```

Both hashChanges trigger the JQM function `$.mobile._handleHashChange` which triggers the actual changePage. The problem is sometimes the events fire in wrong order, sometimes only one fires (if no pushstate support) and for multiview, the last backwards transition doesn't pass anything (`no to defined`) , so JQM just reloads the first page, while in multiview I need to change to the first page on the panel. 

If you check my code in `maineventbindings` the `pagebeforechange` handler does all the blocking already and also has a workaround for the last backwards transition ('BACKFIX'). 

So this should not break the history, because it took me forever to get it right. I have the first culprits, one being my listener for `pageremove` which I used to prevent JQM from removing a wrapper page, when only the panel page should be removed. Trying to fix this now and see how it work.

**Comment by sstraus** [comment] 2012-08-22 10:04
Sure, but my pages are not ajax, are already there in the right panel. Does this affect the behaviour?

**Comment by frequent** [comment] 2012-08-22 10:23
Should still be the same, because that's how the Jquery Mobile navigation works. They always run 2 events (one string/one object).

**Comment by frequent** [comment] 2012-08-22 10:40
I think I found the problem. Going down "2 levels" on any panel and then trying to go back fires a regular JQM backwards transition and not a panel backwards transition. Let's see if I can fix.

**Comment by sstraus** [comment] 2012-08-22 10:56
Yes it is. I found the same.

**Comment by sstraus** [comment] 2012-08-22 10:58
BTW About the Portrait I get the issue in Chrome too, just resizing the window width.

**Comment by frequent** [comment] 2012-08-22 11:06
first things first :-)

**Comment by frequent** [comment] 2012-08-22 12:06
I more or less have it. I think the problem is in the sitemap array I'm using to keep track of which pages are loaded and which I'm checking for existing entries on backwards transitions. Currently I'm only storing ... crap.... and not the URL of the pages being called :-) Fixing this tonight. 

If you want to check if this is the cause, go to the `panelHash` function (about line 1770) and insert a consoles 

1)  after the var declarations:

```
  console.log( o.sitemap)
```

Check if there is something in there and if so, if the name of the included object is `0` or matches the URL of the page you want to load.

2) inside the next if statement, which determines whether multiview (IF) or JQM (ELSE) handles the transition.

```
 IF:   console.log( "done by multiview" )
 ELSE: console.log( "done by JQM")
```

Should be multiview, probably is JQM. That's the error on my page. I will try to fix tonight and commit.

**Comment by sstraus** [comment] 2012-08-22 14:34
the o.sitemap is alway undefined, o.siteMap is an empty object. But when the panel become blank the transition is done by JQM.

**Comment by frequent** [comment] 2012-08-22 14:42
Ok. That's the problem. I'm fixing this tonight, then let's see if this helps. Should. Thanks for checking.

**Comment by frequent** [comment] 2012-08-22 21:04
Ok. Commited a fix in the JQM 1.2 version. I tried it in my current project, where I have a listview in the menu and load corresponding pages in the main section. Previously I could load pages but could not go back (broke the page). 

This works now, so I can do this:

```
action                menu            main
-----------------------------------------------------
init                      A1                 B1
A1 > load B2       A1                 B2
A1 > load B3       A1                 B3
browser back       A1                 B2
A1 > load B4       A1                 B4
browser back       A1                 B2
browser back       A1                 B1
```

This should also work the other way around or "in the mix". Please let me know if it works any better now. 

Regarding popovers: I see what you mean. Happens when you start in portrait. Trying to see what's wrong with it now.

**Comment by frequent** [comment] 2012-08-23 09:05
Also fixed the popover button. It was missing a class. I can do the following now:

```
action                menu            main
-----------------------------------------------------
start in portrait     A1                B1
open popover
load page            A1                 B2
browser back       A1                 B1
change to landscape
load page            A1                 B2
browser back       A1                 B1
```

I'm closing this. If you still have problems, please re-open. But I think yesterdays fix more or less also fixed the behavior with the popover panel and page changes. This last fix was only for adding a missing class name.

**Closed as completed by frequent** 2012-08-23 09:05 UTC

**Comment by sstraus** [comment] 2012-08-23 11:05
I still have troubles, I'll investigate this weekend.

Thank you!

**Comment by frequent** [comment] 2012-08-23 11:34
ok. If you want to check what's happening, put consoles here (lines from current multiview version)

```
line 1738 - panelTrans: function (e, data) {
     console.log( "panel transition FWD"); 

line 1769 - o._trans = "panelTrans";
     console.log( "parameters:"); 
     console.log( data.toPage ); 
     console.log( data.options.fromPage.attr('id') );
     console.log( data.options.pageContainer.jqmData('id') );

line 1774 - } else {
     console.log( "JQM transition"); 

line 1825 ... || !o.siteMap[data.toPage] == false     ) {
     console.log( "panel transition BACK"); 

line 1911 ... data.options.reverse = true;
     console.log( "parameters:"); 
     console.log( data.toPage ); 
     console.log( data.options.fromPage.attr('id') );
     console.log( data.options.pageContainer.jqmData('id') );

line 1916 ...  } else {
     console.log( "JQM transition");      

line 1945  isHash, isPage;  
      console.log( "panel transition CLEANUP"); 

line 2077  }
      console.log( "JQM history");   
      console.log(  $.mobile.urlHistory.stack);   
      console.log(  $.mobile.urlHistory.activeIndex);
      console.log(  o.siteMap  );

line 2218 - $(document).on( "pagebeforechange", function( e, data ) {...    
     console.log( "pagebeforechange detected");

line 2299 - uncomment  // console.log("BACKFIX"); = sets override for last backwards transition on a panel
line 2321 - uncomment  // console.log("BLOCK7"); = blocks trailing object on panel transitions
```

Keys are
1) for both FWD and BACK panel transitions, you have to make sure, you don't land in "JQM transition", because panel transitions must go through the panel transition handler (JQM does not care for panels)
2) for both FWD and BACK panel transitions, the three parameters need to be set. If one turns up an empty string or object, you will get an error. 
3) after the CLEANUP, the history should not have any double entries (now also done by JQM), activeIndex should not be negative, sitemap is there just for good measure

**Comment by sstraus** [comment] 2012-08-23 21:01
I get those signifcant debug lines?

JQM transition multiview.js:1926
panel transition CLEANUP multiview.js:1954
JQM history multiview.js:2085
[
Object
pageContainer: e.fn.e.init[1]
pageUrl: "/C:/Users/stefano/Documents/My%20Dropbox/jsproj/OfflineMobile/index.htm"
role: undefined
title: "TUMobile"
transition: "none"
url: "/C:/Users/stefano/Documents/My%20Dropbox/jsproj/OfflineMobile/index.htm"
**proto**: Object
**defineGetter**: function **defineGetter**() { [native code] }
**defineSetter**: function **defineSetter**() { [native code] }
**lookupGetter**: function **lookupGetter**() { [native code] }
**lookupSetter**: function **lookupSetter**() { [native code] }
constructor: function Object() { [native code] }
hasOwnProperty: function hasOwnProperty() { [native code] }
isPrototypeOf: function isPrototypeOf() { [native code] }
propertyIsEnumerable: function propertyIsEnumerable() { [native code] }
toLocaleString: function toLocaleString() { [native code] }
toString: function toString() { [native code] }
valueOf: function valueOf() { [native code] }
, 
Object
pageContainer: e.fn.e.init[1]
pageUrl: "side_list"
role: undefined
title: "TUMobile"
transition: "fade"
url: "side_list"
**proto**: Object

**Comment by sstraus** [comment] 2012-08-26 21:48
Any idea on how to handle this? I can also build a prototype if needed.

**Comment by Golodhros** [comment] 2012-08-26 21:54
Hi,I am also in a great need of solving this bug. We are going to release a product with Multiview in the tablet version really soon. I'm afraid though that I won't be able to help with the development, but I could definitely help you with the testing!

Many thanks for your great work!

**Comment by frequent** [comment] 2012-08-26 22:01
@sstraus - prototype would be nice. I still haven't been able to reproduce but maybe I'm looking in the wrong direction.

**Comment by frequent** [comment] 2012-08-28 20:03
@sstraus - thanks. I see the problem now. Let me see if I can fix it.

**Comment by frequent** [comment] 2012-08-28 20:42
@sstraus @Golodhros 

Fixed. Please try [here](http://www.franckreich.de/jqm/proto.htm)

I fixed a similar problem yesterday, where requireJS somehow triggered two pagechange events on the initial page load. The 2nd pagechange tried to go from `myFirstPage` to `myFirstPage` which is blocked inside Jquery Mobile, but is still running through all the processes in multiview. To fix my problem, on `pagebeforechange` I checked for **data.toPage[object]** whether **toPage** and **fromPage** matched (= same page transition) and whether **data.options.allowSamePageTransition="false" (default)**. If so, stop. 

Your problem was the same, except you ware passing in **data.toPage[string]**. I added another check to also stop and now it works. 

I will try to put my fix and this one into a single fix, but for the moment you should be ok with the multiview in the link above. 

Please also use the JQM version in there. In my last copy of JQM latest I somehow missed copying two lines. You will notice if you use more than one slider on a page...

**Comment by sstraus** [comment] 2012-08-29 06:56
Thank you, it works!

S.

Da: Sven Franck [mailto:notifications@github.com]
Inviato: martedì 28 agosto 2012 22:42
A: frequent/multiview
Cc: Stefano Straus
Oggetto: Re: [multiview] Changing a panel twice will corrupt history (#40)

@sstraushttps://github.com/sstraus @Golodhroshttps://github.com/Golodhros

Fixed. Please try herehttp://www.franckreich.de/jqm/proto.htm

I fixed a similar problem yesterday, where requireJS somehow triggered two pagechange events on the initial page load. The 2nd pagechange tried to go from myFirstPage to myFirstPage which is blocked inside Jquery Mobile, but is still running through all the processes in multiview. To fix my problem, on pagebeforechange I checked for data.toPage[object] whether toPage and fromPage matched (= same page transition) and whether data.options.allowSamePageTransition="false" (default). If so, stop.

Your problem was the same, except you ware passing in data.toPage[string]. I added another check to also stop and now it works.

I will try to put my fix and this one into a single fix, but for the moment you should be ok with the multiview in the link above.

Please also use the JQM version in there. In my last copy of JQM latest I somehow missed copying two lines. You will notice if you use more than one slider on a page...

**Comment by Golodhros** [comment] 2012-08-30 18:22
In my case it became worse!

I have a list of elements in the menu panel and I load their descriptions in the main panel. When I apply your fix, I cannot load a second element description from the menu panel, it simply stopped to work. So I cannot use it at all.

Maybe my problem was slightly different. When I navigate through different element descriptions, when I go back with the buttons it works the first time, but as long I start again, when I go back, I get the blank page.

Thanks for your work!

**Comment by frequent** [comment] 2012-08-30 19:24
hm. also not sure i understand what you mean. you have a menue with links which load pages in the main section? you can go back and forth allright? but when you refresh the page while going back and forth it breaks? if you can do a sample or send some screenshots with a decription i can try and have a look

**Comment by Golodhros** [comment] 2012-08-30 21:09
Well, I will give you an example:
If I have a menu with elements (A, B, C, D) and I push first A, I will load A details in the main pane. If then I push B, I will load B details, and so on. Then, when I click in the back button, it will work fine, and I will arrive to the initial content of the main pane (the one that was before loading A). Until here, everything works fine.

Now, If I start again clicking in D, it loads D details, I click in B and loads B details, but if I start pushing the Back button, it won't arrive to the initial screen, but to a blank page. So that it works the first time I use the back button, but not the second time I use it. 

It happens also with just one iteration: if I click in A, click in Back, click in B, and click Back, I get a blank consistently.

Thanks!

**Comment by frequent** [comment] 2012-08-30 21:29
ok, i will test that. Hm. Seems broken. I will try to fix.
