### ISSUE TITLE
Width:25%,min-width:250px also inline

### ISSUE THREAD

**Issue by PeterEmanuel** [frequent/multiview#5] opened 2012-03-13 08:40 UTC
Hello Sven,

First, thanks for working on this very promising plugin, exactly what I am needing for a mobile project I'm working on. 

Q1.
I noticed that although the initial width parameters for the left menu panel are set as options, they are also used inline in the jQ code. I tried to change them to other values (e.g. 33%, 320px), but the margin-left for the right panel is then not computed correctly (it should be set to the computed width of the left panel).

Q2.
I also noticed that several methods are currently commented out, like checkWidth(), splitView(), popupBtn()... Is this intentional? Are they no longer required or are they work in progress?

Q3.
I also noticed that you have included a version of ScrollView(). Does this mean that MultiView user's should not include the current standalone version of ScrollView?

Thanks!

Peter

**Comment by PeterEmanuel** [comment] 2012-03-13 08:46
PS: I can fix the width issues in my version (by setting both to 320px for now). 33% did not work well with 320px. But they shouldn't be repeated inline ;-)

**Comment by frequent** [comment] 2012-03-13 09:35
Hey Peter,

Q1 - yes, there's option for it, but I did not integrate them yet. 

If you set your own with, you will have to set the width on BOTH the panel and contained pages! Setting panel alone will not work. I had to set it up like this, because I wanted to keep the panel>page>content similar to JQM treating body>page>content. So panels behave like the body being a _ui-mobile-viewport_ and thus get CSS position:static. Since pages are CSS pos:absolute/relative they flow "out of the viewport" (if it's the body, no problem, if it's the menu doesn't work).  

Q2 - work in progress. Let me update to the latest code, because the functions you mention should be active. Commit coming up. 

Q3 - Correct, I'm using scrollview (and easing), but inside multiview I'm only triggering the scrollview plugin (check scrollMe() function), so you will still need the regular scrollview.js along multiview. 

Scrollview is currently only used for popover panels on touch devices > 468px, in order to make the popup panels scrollable. I had the menu scrollable, too originally, but this still needs work, so currently the menu just scrolls along with the main section.

I will replace scrollview with overthrow eventually, since this seems the way to go - http://filamentgroup.github.com/Overthrow/. Still sitting over RC1 though. 

Let me know if you have any problems with the latest commit.

**Comment by PeterEmanuel** [comment] 2012-03-14 11:53
Thanks Sven! Are you sure there are no important updates in the CSS? When I try to use your latest update, my pages all get (and keep) the display:none from the (old) CSS. The data-show="first" no longer seems to force the initial pages in the menu and main section to be shown on app init.

Cheers

**Comment by frequent** [comment] 2012-03-14 12:02
uhm... forgot to commit the CSS... give me a minute.

**Comment by frequent** [comment] 2012-03-14 12:11
Try again. I'm knee deep in a project using multiview, which should end last week of March. I will then try to clean up my repo and set up a proper demo page with all the infos. Until then I can only copy&paste from my project. 

Let me know if you still have problems. Then I will try to do some prelim cleaning and testing to make sure everything works as expected.

**Comment by PeterEmanuel** [comment] 2012-03-14 12:42
I did, and it appeared that the plugin no longer initialized itself. Starting to debug the init code at the end of the multiview js file, I found out that using bind() instead of the new on() made it initialize again (!!) This is bizar, as on() now should replace both bind() and live(). I am using jQuery 1.7.1 and your modification of jQM. Anyway, thanks, I can now continue with setting up my app.

**Comment by frequent** [comment] 2012-03-14 12:53
Ok. I think this is related to this https://github.com/jquery/jquery-mobile/issues/3696

Actually I don't understand why I need to make my first page JQM bindings using on() BEFORE JQM itself vs. using bind() whenever I want, but the fiddle provided works.... 

I took a note and will see, if I can switch from triggering by binding to pagecreate to using a JQM-init like data-multiview="true" on the page. Then it should just run once the page is parsed. I guess... still trying to understand on/off :-)

**Comment by frequent** [comment] 2012-04-20 20:48
@PeterEmanuel 

new multiview version using JQM 1.1. is up. Still needs fine tuning, but most of the stuff you asked in the issue is taken care off. 
Q1 - all three panels (menu, middle, main) are option-able now
Q2 - cleanup up the code, plus fully commented all functions. I'm down to 9k gzipped. 
Q3 - scrollview is out, overthrow is in. Still fixing up the sample page (not working right now).

Here is a template with [sample navigation](http://www.stokkers.mobi/jqm/multiview/sample-nav.html)

Here is a template with [sample overthrow](http://stokkers.mobi/jqm/multiview/sample-over.html)

Closing this for now.

**Closed as completed by frequent** 2012-04-20 20:48 UTC
